import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import Text from '../components/Text/Text';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [src, setSrc] = useState('');
  const [bandName, setBandName] = useState('');
  useEffect(() => {
    const getBand = async () => {
      const res = await fetch('/api/bands');
      const data = await res.json();
      const { name, image } = data.at(Math.floor(Math.random() * data.length));
      setBandName(name);
      setSrc(image);
    };
    getBand();
  }, []);

  return (
    <div>
      <Head>
        <title>Listen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home}>
        <header className={styles.header}>
          <Text>
            <Link href="/" className="link">
              Listen
            </Link>
          </Text>
          <ul className={styles.nav}>
            <li>
              <Text>
                <Link href="/bands" className="link">
                  Bands
                </Link>
              </Text>
            </li>
            <li>
              <Text>
                <Link href="/albums" className="link">
                  Albums
                </Link>
              </Text>
            </li>
          </ul>
        </header>
        <div className={styles.band}>
          <Text>Featured today:</Text>
          <div className={styles.bandhead}>
            <Text>{bandName}</Text>
            <img
              src={src}
              alt=""
              width={400}
              height={400}
              className={`card ${styles.bandimg}`}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
