import Head from 'next/head';
import Link from 'next/link';
import Text from '../components/Text/Text';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Text>Listen</Text>
        <Text>
          <Link href="/bands">Bands</Link>
        </Text>
        <Text>
          <Link href="/albums">Albums</Link>
        </Text>
      </main>
    </div>
  );
}
